---
- name: Create main folder and subfolders, and copy syslog file
  hosts: localhost
  # Use this vars only if ssh port has error
  # if need to install sudo apt install sshpass
  vars:
    ansible_ssh_user: "jkvcombo"
    ansible_ssh_pass: "Kenneth1220"
  tasks:
    - name: Create main folder
      file:
        path: /home/jkvcombo/Downloads/main/
        state: directory

    - name: Create subfolder sub1
      file:
        path: /home/jkvcombo/Downloads/main/sub1/
        state: directory

    - name: Create subfolder sub2
      file:
        path: /home/jkvcombo/Downloads/main/sub2/
        state: directory

    - name: Copy syslog file to sub1
      copy:
        src: /var/log/syslog
        dest: /home/jkvcombo/Downloads/main/sub1/syslog
